timezone:   Europe/Berlin
excerpt_separator: "\n"
permalink:  "/:year/:month/:day/:title/"
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
            